const DMN_TPO_USUARIO = require("./DMN_TPO_USUARIO");
const DMN_FUNCOES = require("./DMN_FUNCOES");

module.exports = {
  DMN_FUNCOES: DMN_FUNCOES.DMN_FUNCOES,
  DMN_TPO_USUARIO: DMN_TPO_USUARIO.DMN_TPO_USUARIO
}