-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PIC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PIC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PIC` DEFAULT CHARACTER SET utf8 ;
USE `PIC` ;

-- -----------------------------------------------------
-- Table `PIC`.`TB_EMPRESA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIC`.`TB_EMPRESA` ;

CREATE TABLE IF NOT EXISTS `PIC`.`TB_EMPRESA` (
  `PK_EMPRESA` INT NOT NULL AUTO_INCREMENT,
  `COD_EMPRESA` VARCHAR(5) NOT NULL,
  `CNPJ_EMPRESA` VARCHAR(13) NOT NULL,
  `EMAIL_EMPRESA` VARCHAR(50) NOT NULL,
  `TEL_EMPRESA` VARCHAR(15) NOT NULL,
  `ENDER_EMPRESA` VARCHAR(100) NOT NULL COMMENT 'Endereco',
  `INSCR_EMPRESA` VARCHAR(45) NOT NULL COMMENT 'INCRICAO empresa\n',
  PRIMARY KEY (`PK_EMPRESA`),
  UNIQUE INDEX `COD_EMPRESA_UNIQUE` (`COD_EMPRESA` ASC),
  UNIQUE INDEX `CNPJ_EMPRESA_UNIQUE` (`CNPJ_EMPRESA` ASC),
  UNIQUE INDEX `PK_EMPRESA_UNIQUE` (`PK_EMPRESA` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIC`.`TD_TPO_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIC`.`TD_TPO_USUARIO` ;

CREATE TABLE IF NOT EXISTS `PIC`.`TD_TPO_USUARIO` (
  `PK_TPO_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `DESC_TPO_USUARIO` VARCHAR(45) NOT NULL,
  `COD_TPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`PK_TPO_USUARIO`),
  UNIQUE INDEX `COD_TPO_USUARIO_UNIQUE` (`COD_TPO_USUARIO` ASC),
  UNIQUE INDEX `PK_TPO_USUARIO_UNIQUE` (`PK_TPO_USUARIO` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIC`.`TB_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIC`.`TB_USUARIO` ;

CREATE TABLE IF NOT EXISTS `PIC`.`TB_USUARIO` (
  `PK_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `FK_TPO_USUARIO` INT NOT NULL,
  `COD_USUARIO` VARCHAR(5) NOT NULL,
  `EMAIL_USUARIO` VARCHAR(50) NOT NULL,
  `TEL_USUARIO` VARCHAR(15) NOT NULL,
  `SNA_USUARIO` VARCHAR(60) NOT NULL COMMENT 'SENHA',
  PRIMARY KEY (`PK_USUARIO`),
  UNIQUE INDEX `PK_USUARIO_UNIQUE` (`PK_USUARIO` ASC),
  UNIQUE INDEX `COD_USUARIO_UNIQUE` (`COD_USUARIO` ASC),
  INDEX `fk_TB_USUARIO_TD_TPO_USUARIO1_idx` (`FK_TPO_USUARIO` ASC),
  CONSTRAINT `fk_TB_USUARIO_TD_TPO_USUARIO1`
    FOREIGN KEY (`FK_TPO_USUARIO`)
    REFERENCES `PIC`.`TD_TPO_USUARIO` (`PK_TPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIC`.`TB_FUNCOES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIC`.`TB_FUNCOES` ;

CREATE TABLE IF NOT EXISTS `PIC`.`TB_FUNCOES` (
  `PK_FUNCOES` INT NOT NULL AUTO_INCREMENT,
  `COD_FUNCOES` INT NOT NULL,
  `DESC_FUNCOES` VARCHAR(45) NOT NULL,
  `FK_EMPRESA` INT NOT NULL,
  PRIMARY KEY (`PK_FUNCOES`),
  UNIQUE INDEX `PK_FUNCOES_UNIQUE` (`PK_FUNCOES` ASC),
  UNIQUE INDEX `COD_FUNCOES_UNIQUE` (`COD_FUNCOES` ASC),
  INDEX `fk_TB_FUNCOES_TB_EMPRESA1_idx` (`FK_EMPRESA` ASC),
  CONSTRAINT `fk_TB_FUNCOES_TB_EMPRESA1`
    FOREIGN KEY (`FK_EMPRESA`)
    REFERENCES `PIC`.`TB_EMPRESA` (`PK_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIC`.`TA_USUARIO_EMP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIC`.`TA_USUARIO_EMP` ;

CREATE TABLE IF NOT EXISTS `PIC`.`TA_USUARIO_EMP` (
  `PK_USUARIO_EMP` INT NOT NULL AUTO_INCREMENT,
  `FK_USUARIO` INT NOT NULL,
  `FK_EMPRESA` INT NOT NULL,
  `FK_FUNCOES` INT NOT NULL,
  PRIMARY KEY (`PK_USUARIO_EMP`),
  UNIQUE INDEX `PK_USUARIO_EMP_UNIQUE` (`PK_USUARIO_EMP` ASC),
  INDEX `fk_TA_USUARIO_EMP_TB_USUARIO1_idx` (`FK_USUARIO` ASC),
  INDEX `fk_TA_USUARIO_EMP_TB_EMPRESA1_idx` (`FK_EMPRESA` ASC),
  INDEX `fk_TA_USUARIO_EMP_TB_FUNCOES1_idx` (`FK_FUNCOES` ASC),
  CONSTRAINT `fk_TA_USUARIO_EMP_TB_USUARIO1`
    FOREIGN KEY (`FK_USUARIO`)
    REFERENCES `PIC`.`TB_USUARIO` (`PK_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TA_USUARIO_EMP_TB_EMPRESA1`
    FOREIGN KEY (`FK_EMPRESA`)
    REFERENCES `PIC`.`TB_EMPRESA` (`PK_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TA_USUARIO_EMP_TB_FUNCOES1`
    FOREIGN KEY (`FK_FUNCOES`)
    REFERENCES `PIC`.`TB_FUNCOES` (`PK_FUNCOES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIC`.`TB_PROJETO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIC`.`TB_PROJETO` ;

CREATE TABLE IF NOT EXISTS `PIC`.`TB_PROJETO` (
  `PK_PROJETO` INT NOT NULL AUTO_INCREMENT,
  `COD_PROJETO` INT NOT NULL,
  `DESC_PROJETO` VARCHAR(45) NOT NULL,
  `FK_EMPRESA` INT NOT NULL,
  PRIMARY KEY (`PK_PROJETO`),
  UNIQUE INDEX `PK_PROJETO_UNIQUE` (`PK_PROJETO` ASC),
  UNIQUE INDEX `COD_PROJETO_UNIQUE` (`COD_PROJETO` ASC),
  INDEX `fk_TB_PROJETO_TB_EMPRESA1_idx` (`FK_EMPRESA` ASC),
  CONSTRAINT `fk_TB_PROJETO_TB_EMPRESA1`
    FOREIGN KEY (`FK_EMPRESA`)
    REFERENCES `PIC`.`TB_EMPRESA` (`PK_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PIC`.`TD_TPO_USUARIO`
-- -----------------------------------------------------
START TRANSACTION;
USE `PIC`;
INSERT INTO `PIC`.`TD_TPO_USUARIO` (`PK_TPO_USUARIO`, `DESC_TPO_USUARIO`, `COD_TPO_USUARIO`) VALUES (1, 'Lider', 1);
INSERT INTO `PIC`.`TD_TPO_USUARIO` (`PK_TPO_USUARIO`, `DESC_TPO_USUARIO`, `COD_TPO_USUARIO`) VALUES (2, 'Comum', 2);
INSERT INTO `PIC`.`TD_TPO_USUARIO` (`PK_TPO_USUARIO`, `DESC_TPO_USUARIO`, `COD_TPO_USUARIO`) VALUES (3, 'Admin', 3);

COMMIT;

